name: Plugin tests
run-name: Plugin tests in [${{ github.ref_name }}] @${{ github.actor }}

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pongo
        run: |
          (cd /tmp && git clone https://github.com/Kong/kong-pongo.git)
          sudo ln -sf /tmp/kong-pongo/pongo.sh /usr/local/bin/pongo
          sudo chmod +x /usr/local/bin/pongo

      - name: Run tests
        run: |
          make test
